#!/usr/bin/env node
// Rebuilds the per-context README indexes and the global ROADMAP from plan
// frontmatter (status/type/priority/context). Status is derived from checkbox
// progress when a plan has any, otherwise from the frontmatter `status`.
//
// Usage: npm run docs:index   (or: node scripts/update-docs.mjs)

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONTEXTS_DIR = join(ROOT, 'docs', 'contexts');

const STATUS = {
  'in-progress': { emoji: '🚧', label: 'In progress', rank: 0 },
  draft: { emoji: '📋', label: 'Draft', rank: 1 },
  done: { emoji: '✅', label: 'Done', rank: 2 },
  outdated: { emoji: '🗑️', label: 'Outdated', rank: 3 },
};
const PRIORITY = {
  critical: { label: '🔴 Critical', rank: 0 },
  high: { label: '🟠 High', rank: 1 },
  medium: { label: '🟡 Medium', rank: 2 },
  low: { label: '🟢 Low', rank: 3 },
};

function parseFrontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---/);
  const data = {};
  if (match) {
    for (const line of match[1].split('\n')) {
      const idx = line.indexOf(':');
      if (idx > 0) data[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
    }
  }
  return data;
}

function firstHeading(text) {
  const match = text.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : null;
}

function deriveStatus(text, fallback) {
  const done = (text.match(/- \[x\]/gi) || []).length;
  const todo = (text.match(/- \[ \]/g) || []).length;
  if (done + todo === 0) return fallback;
  if (todo === 0) return 'done';
  if (done === 0) return fallback === 'done' ? 'in-progress' : fallback;
  return 'in-progress';
}

const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const titleCase = (s) => s.split('-').map(cap).join(' ');

function collectPlans() {
  const plans = [];
  for (const ctx of readdirSync(CONTEXTS_DIR)) {
    const ctxDir = join(CONTEXTS_DIR, ctx);
    if (!statSync(ctxDir).isDirectory()) continue;
    for (const file of readdirSync(ctxDir)) {
      if (!file.endsWith('.md') || file === 'README.md' || file === 'architecture.md') continue;
      const text = readFileSync(join(ctxDir, file), 'utf8');
      const fm = parseFrontmatter(text);
      plans.push({
        context: ctx,
        slug: file,
        title: firstHeading(text) ?? file.replace(/\.md$/, ''),
        status: STATUS[deriveStatus(text, fm.status || 'draft')] ? deriveStatus(text, fm.status || 'draft') : 'draft',
        type: fm.type || 'feature',
        priority: PRIORITY[fm.priority] ? fm.priority : 'medium',
      });
    }
  }
  return plans;
}

function writeContextIndexes(plans) {
  const contexts = [...new Set(plans.map((p) => p.context))].sort();
  for (const ctx of contexts) {
    const rows = plans
      .filter((p) => p.context === ctx)
      .sort((a, b) => STATUS[a.status].rank - STATUS[b.status].rank || PRIORITY[a.priority].rank - PRIORITY[b.priority].rank);
    const lines = [
      `# ${titleCase(ctx)}`,
      '',
      '_Auto-generated by `npm run docs:index`. Do not edit by hand — edit plan frontmatter instead._',
      '',
      '| Status | Plan | Type | Priority |',
      '|--------|------|------|----------|',
      ...rows.map(
        (p) => `| ${STATUS[p.status].emoji} ${STATUS[p.status].label} | [${p.title}](${p.slug}) | ${cap(p.type)} | ${cap(p.priority)} |`,
      ),
    ];
    writeFileSync(join(CONTEXTS_DIR, ctx, 'README.md'), `${lines.join('\n')}\n`);
  }
}

function writeRoadmap(plans) {
  const active = plans
    .filter((p) => p.status === 'draft' || p.status === 'in-progress')
    .sort((a, b) => PRIORITY[a.priority].rank - PRIORITY[b.priority].rank || STATUS[a.status].rank - STATUS[b.status].rank);
  const lines = [
    '# YouScan Dashboard Roadmap',
    '',
    '_Auto-generated by `npm run docs:index`. Active plans (draft + in-progress) across all contexts, grouped by priority._',
    '',
  ];
  for (const pr of Object.keys(PRIORITY)) {
    const group = active.filter((p) => p.priority === pr);
    if (!group.length) continue;
    lines.push(`## ${PRIORITY[pr].label}`, '', '| Context | Plan | Status |', '|---|---|---|');
    for (const p of group) {
      lines.push(`| ${p.context} | [${p.title}](contexts/${p.context}/${p.slug}) | ${STATUS[p.status].emoji} ${STATUS[p.status].label} |`);
    }
    lines.push('');
  }
  if (!active.length) lines.push('_No active plans — everything shipped. 🎉_', '');
  writeFileSync(join(ROOT, 'docs', 'ROADMAP.md'), `${lines.join('\n')}\n`);
}

if (!existsSync(CONTEXTS_DIR)) {
  console.log('No docs/contexts directory yet — nothing to index.');
  process.exit(0);
}

const plans = collectPlans();
writeContextIndexes(plans);
writeRoadmap(plans);
console.log(`Indexed ${plans.length} plan(s) across ${new Set(plans.map((p) => p.context)).size} context(s).`);
